### ISSUE TITLE
Installing components

### ISSUE THREAD

**Issue by jagi** [ecwyne/meteor-polymer#11]
I've installed few components using `bower install` from command line being in `public` directory. Now when I start meteor project polymer package is trying to download polymer one more time and it shouldn't and it creates **public** folder inside **public** folder etc.

In your [polymer-elements package](https://github.com/ecwyne/meteor-polymer-elements) you are using this piece of code to download elements:

```
var dir = path.join(path.relative(process.cwd(), process.env.PWD), 'public/bower_components');
Bower.install(['Polymer/core-elements#0.4.0', 'Polymer/paper-elements'], {save: true}, {directory: dir});
```

I don't think that users of your package should use this kind of solution to import components. Could you describe the process of importing components?

**Comment by ecwyne** [comment]
Totally new method with new package.
