### ISSUE TITLE
Slow reload

### ISSUE THREAD

**Issue by lukejagodzinski** [ecwyne/meteor-polymer#12]
After installing this package any change to my Meteor project causes everything to stuck. I can't do anything and even browser reload doesn't help. I have to type address one more time (without any route). After uninstalling package everything works well. It seems to be problem with initialisation of the polymer. Probably it tries to download Polymer on every reload.

**Comment by boxxa** [comment]
Found this thread after having this issue. It's not a code issue. If you are using the default file structure, the problem shows up. Create your client and server folders and move your code out of isClient. This resolved it for me.
