### ISSUE TITLE
configuring components path

### ISSUE THREAD

**Issue by jagi** [ecwyne/meteor-polymer#17]
Hi thanks again for great work with this package.
It would be great if you could make components path configurable. For example:

```js
MeteorPolymer.config({
  "directory" : "public/components"
});
```

or just read .bowerrc for path to components

**Comment by rcampoamor** [comment]
I was setting this up for the first time and noticed that if you don't have a .bowerrc file indicating where the local components are, the meteor startup fails with this error:  Error: Request to https://bower.herokuapp.com/packages/polymer failed with 503  Which would (incorrectly) indicate that the call to the herokuapp was failing.
