### ISSUE TITLE
meteor add ecwyne:polymer interferes with template event binding

### ISSUE THREAD

**Issue by mattybow** [ecwyne/meteor-polymer#19]
I loaded the polymer dependencies as instructed and got the `<paper-button>`s to render correctly but for some reason some of the template events are not being bound in Safari 8.0 of FF 34.0  
I've attached simple `'click'` events on the header and footer templates, also removed `<paper-button>` elements and the events still won't work unless I `meteor remove ecwyne:polymer`.
For a more detailed explanation, see this [stack question](http://stackoverflow.com/questions/27238810/meteor-iron-router-with-polymer-paper-button-not-routing-and-iron-router-layout)

**Comment by schnie** [comment]
If anyone is still having these issues, check out the fix I mentioned here https://github.com/Differential/polymer-demo/issues/6

hopefully it helps!
