### ISSUE TITLE
platform.js to webcomponents.js breaking

### ISSUE THREAD

**Issue by charleswinin** [ecwyne/meteor-polymer#23]
Changing the line:
```
<script type="text/javascript" src="bower_components/platform/platform.js"></script>
```
to
```
<script type="text/javascript" src="bower_components/webcomponentsjs/webcomponents.js"></script>
```
causes breaks.

I think its a polymer v0.5.0 to v0.5.1 issue. Anyway to solve this?

**Comment by ecwyne** [comment]
newest package version should fix this. You should not need to import `webcomponents.js` yourself, it's done for you.
