### ISSUE TITLE
Console error after running meteor add ecwyne:polymer and meteor add ecwyne:polymer-elements

### ISSUE THREAD

**Issue by ajaysharma2007** [ecwyne/meteor-polymer#25]
Hi,
  After running the following commands on the meteor app console error is showing up:
  Commands(ran in same order):
     meteor add ecwyne:polymer
     meteor add ecwyne:polymer-elements

  Error:
    Uncaught TypeError: Cannot read property 'resolveDom' of undefined
    Error file location: http://localhost:3000/bower_components/polymer/src/declaration/path.js

Meteor Version:
      Meteor 1.0.3.2

None of the meteor app files has been modified.
![screen shot 2015-03-16 at 11 22 22 pm](https://cloud.githubusercontent.com/assets/4421186/6682272/55e9990a-cc33-11e4-80a4-78ce2ab4d054.png)

Thanks
Ajay

**Comment by ecwyne** [comment]
You do NOT need to add `ecwyne:polymer`

the `ecwyne:polymer-elements` automatically adds the polymer base for you.
